# Generated by Django 4.0.1 on 2022-02-13 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garden_plot', models.PositiveIntegerField(blank=True, verbose_name='Номер участка')),
                ('is_data_entered_this_month', models.BooleanField(verbose_name='Показатели счетчиков уже переданы в этом месяце')),
                ('is_paid_this_month', models.BooleanField(verbose_name='Оплата уже произведена в данном месяце')),
            ],
            options={
                'verbose_name': 'Данные по участку',
                'verbose_name_plural': 'Данные по участкам',
            },
        ),
        migrations.CreateModel(
            name='PhotoOfPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фотография счетчика')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden_backend.garden', verbose_name='Участок в собственности')),
            ],
            options={
                'verbose_name': 'Фото оплаты',
                'verbose_name_plural': 'Фото оплаты',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='ФИО')),
                ('chat_id', models.CharField(blank=True, max_length=100, verbose_name='ID телеграм чата')),
                ('phone_number', models.CharField(blank=True, max_length=100, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Собственник участка',
                'verbose_name_plural': 'Собственники участков',
            },
        ),
        migrations.CreateModel(
            name='MonthMeters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meters', models.PositiveIntegerField(verbose_name='Показания счетчиков')),
                ('time', models.DateTimeField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden_backend.garden', verbose_name='Участок в собственности')),
            ],
            options={
                'verbose_name': 'Данные по ежемесячным показателям',
                'verbose_name_plural': 'Данные по ежемесячным показателям',
            },
        ),
        migrations.AddField(
            model_name='garden',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden_backend.owner', verbose_name='Собственник участка'),
        ),
    ]
